apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: todo-app
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app-deployment
  progressDeadlineSeconds: 60
  service:
    port: 5000
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 90  # At least 90% of requests should succeed
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 3000  # Latency should be below 3s
        interval: 30s
    webhooks:
      - name: load-test
        url: http://loadtester.flagger/
        timeout: 5s
        metadata:
          cmd: "hey -z 10m -q 10 -c 2 http://todo-app-canary.default:5000/"