---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-pods
  namespace: prometheus  
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      istio: monitor
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: stats/prometheus