apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"] # ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-access-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-access-role
subjects:
  - kind: ServiceAccount
    name: myapp
    namespace: default
